/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Nahid Aslam 12
 */
public class Calculator extends javax.swing.JFrame {

    /**
     * Creates new form Calculator
     */
    double num;
    double last;
    double res=0;
    int calculation;
    String operation;
    public Calculator() {
        initComponents();
        jRadioButton1.setEnabled(false);
    }
    public void arithmatic_operation()
    {
        String answer;
        last = Double.parseDouble(jfield.getText());
        switch(calculation)
        {
            case 1:
                res = num + last;
                answer = String.format("%.2f", res);
                jfield.setText((answer));
                break;
            case 2:
                res = num - last;
                answer = String.format("%.2f", res);
                jfield.setText((answer));
                break; 
            case 3:
                res = num * last;
                answer = String.format("%.2f", res);
                jfield.setText((answer));
                break;
            case 4:
                res = num / last;
                answer = String.format("%.2f", res);
                jfield.setText((answer));
                break;    
            case 5:
                res = num % last;
                answer = String.format("%.2f", res);
                jfield.setText((answer));
                break;   
             case 6:
                res =  Double.parseDouble(jfield.getText());
                jfield.setText(Double.toString(Math.sqrt(res)));
                break;   
        }
        //jfield.setText("");
    }
    public void enable()
    {
        jfield.setEnabled(true);
        jRadioButton1.setEnabled(false);
        jRadioButton2.setEnabled(true);
        j1.setEnabled(true);
        j2.setEnabled(true);
        j3.setEnabled(true);
        j4.setEnabled(true);
        j5.setEnabled(true);
        j6.setEnabled(true);
        j7.setEnabled(true);
        j8.setEnabled(true);
        j9.setEnabled(true);
        j0.setEnabled(true);
        C.setEnabled(true);
        CE.setEnabled(true);
        Equal.setEnabled(true);
        MCbutton.setEnabled(true);
        MRbutton.setEnabled(true);
        MSbutton.setEnabled(true);
        Mbtn.setEnabled(true);
        bckspc.setEnabled(true);
        inverse.setEnabled(true);
        jSub.setEnabled(true);
        jToggole.setEnabled(true);
        mod.setEnabled(true);
        sqrt.setEnabled(true);
        jAdd.setEnabled(true);
        jDot.setEnabled(true);
        jMul.setEnabled(true);
        jDiv.setEnabled(true);
    }
    public void disable()
    {
        jfield.setEnabled(false);
        jRadioButton1.setEnabled(true);
        jRadioButton2.setEnabled(false);
        j1.setEnabled(false);
        j2.setEnabled(false);
        j3.setEnabled(false);
        j4.setEnabled(false);
        j5.setEnabled(false);
        j6.setEnabled(false);
        j7.setEnabled(false);
        j8.setEnabled(false);
        j9.setEnabled(false);
        j0.setEnabled(false);
        C.setEnabled(false);
        CE.setEnabled(false);
        Equal.setEnabled(false);
        MCbutton.setEnabled(false);
        MRbutton.setEnabled(false);
        MSbutton.setEnabled(false);
        Mbtn.setEnabled(false);
        bckspc.setEnabled(false);
        inverse.setEnabled(false);
        jSub.setEnabled(false);
        jToggole.setEnabled(false);
        mod.setEnabled(false);
        sqrt.setEnabled(false);
        jAdd.setEnabled(false);
        jDot.setEnabled(false);
        jMul.setEnabled(false);
        jDiv.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jfield = new javax.swing.JTextField();
        j7 = new javax.swing.JButton();
        j8 = new javax.swing.JButton();
        j9 = new javax.swing.JButton();
        j4 = new javax.swing.JButton();
        j5 = new javax.swing.JButton();
        j6 = new javax.swing.JButton();
        j1 = new javax.swing.JButton();
        j0 = new javax.swing.JButton();
        j2 = new javax.swing.JButton();
        jToggole = new javax.swing.JButton();
        j3 = new javax.swing.JButton();
        jDot = new javax.swing.JButton();
        jDiv = new javax.swing.JButton();
        jMul = new javax.swing.JButton();
        jSub = new javax.swing.JButton();
        jAdd = new javax.swing.JButton();
        bckspc = new javax.swing.JButton();
        C = new javax.swing.JButton();
        CE = new javax.swing.JButton();
        MCbutton = new javax.swing.JButton();
        MRbutton = new javax.swing.JButton();
        MSbutton = new javax.swing.JButton();
        Mbtn = new javax.swing.JButton();
        sqrt = new javax.swing.JButton();
        mod = new javax.swing.JButton();
        inverse = new javax.swing.JButton();
        Equal = new javax.swing.JButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Java Calculator");
        setLocation(new java.awt.Point(500, 250));
        setType(java.awt.Window.Type.UTILITY);

        jfield.setBackground(new java.awt.Color(204, 255, 255));
        jfield.setFont(new java.awt.Font("Tahoma", 1, 23)); // NOI18N
        jfield.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jfield.setAutoscrolls(false);
        jfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jfieldActionPerformed(evt);
            }
        });

        j7.setText("7");
        j7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j7ActionPerformed(evt);
            }
        });

        j8.setText("8");
        j8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j8ActionPerformed(evt);
            }
        });

        j9.setText("9");
        j9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j9ActionPerformed(evt);
            }
        });

        j4.setText("4");
        j4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j4ActionPerformed(evt);
            }
        });

        j5.setText("5");
        j5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j5ActionPerformed(evt);
            }
        });

        j6.setText("6");
        j6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j6ActionPerformed(evt);
            }
        });

        j1.setText("1");
        j1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j1ActionPerformed(evt);
            }
        });

        j0.setText("0");
        j0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j0ActionPerformed(evt);
            }
        });

        j2.setText("2");
        j2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j2ActionPerformed(evt);
            }
        });

        jToggole.setText("+/-");
        jToggole.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggoleActionPerformed(evt);
            }
        });

        j3.setText("3");
        j3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j3ActionPerformed(evt);
            }
        });

        jDot.setText(".");
        jDot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDotActionPerformed(evt);
            }
        });

        jDiv.setText("/");
        jDiv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDivActionPerformed(evt);
            }
        });

        jMul.setText("*");
        jMul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMulActionPerformed(evt);
            }
        });

        jSub.setText("-");
        jSub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSubActionPerformed(evt);
            }
        });

        jAdd.setText("+");
        jAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAddActionPerformed(evt);
            }
        });

        bckspc.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        bckspc.setForeground(new java.awt.Color(153, 0, 0));
        bckspc.setText("Backspc");
        bckspc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bckspcActionPerformed(evt);
            }
        });

        C.setFont(C.getFont().deriveFont(C.getFont().getStyle() | java.awt.Font.BOLD));
        C.setForeground(new java.awt.Color(153, 0, 0));
        C.setText("C");
        C.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CActionPerformed(evt);
            }
        });

        CE.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        CE.setForeground(new java.awt.Color(153, 0, 0));
        CE.setText("CE");
        CE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CEActionPerformed(evt);
            }
        });

        MCbutton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        MCbutton.setForeground(new java.awt.Color(153, 0, 0));
        MCbutton.setText("MC");
        MCbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MCbuttonActionPerformed(evt);
            }
        });

        MRbutton.setFont(MRbutton.getFont().deriveFont(MRbutton.getFont().getStyle() | java.awt.Font.BOLD));
        MRbutton.setForeground(new java.awt.Color(153, 0, 0));
        MRbutton.setText("MR");
        MRbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MRbuttonActionPerformed(evt);
            }
        });

        MSbutton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        MSbutton.setForeground(new java.awt.Color(153, 0, 0));
        MSbutton.setText("MS");
        MSbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MSbuttonActionPerformed(evt);
            }
        });

        Mbtn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Mbtn.setForeground(new java.awt.Color(153, 0, 0));
        Mbtn.setText("M+");
        Mbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MbtnActionPerformed(evt);
            }
        });

        sqrt.setText("sqrt");
        sqrt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sqrtActionPerformed(evt);
            }
        });

        mod.setText("%");
        mod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modActionPerformed(evt);
            }
        });

        inverse.setText("1/x");
        inverse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inverseActionPerformed(evt);
            }
        });

        Equal.setText("=");
        Equal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EqualActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jRadioButton1.setText("ON");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jRadioButton2.setText("OFF");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        jLabel1.setForeground(new java.awt.Color(153, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jfield, javax.swing.GroupLayout.DEFAULT_SIZE, 409, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(MSbutton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(MRbutton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(MCbutton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Mbtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jRadioButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jRadioButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(j1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(j0, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(j4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(j7))
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jToggole, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(j2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(j5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(j8, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(j9)
                                        .addComponent(j6, javax.swing.GroupLayout.Alignment.TRAILING))
                                    .addComponent(j3)
                                    .addComponent(jDot))
                                .addGap(31, 31, 31))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(bckspc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(30, 30, 30)
                                .addComponent(C, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(21, 21, 21)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jSub, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jDiv, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jMul, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(inverse, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(mod, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(sqrt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Equal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(CE, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(22, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jfield, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(bckspc, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(C, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(CE)))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jRadioButton1)))
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButton2)
                        .addGap(3, 3, 3)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(j7)
                            .addComponent(MCbutton))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(j4)
                            .addComponent(MRbutton))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(j1)
                            .addComponent(MSbutton))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(j0)
                            .addComponent(Mbtn)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(j8)
                        .addGap(18, 18, 18)
                        .addComponent(j5)
                        .addGap(18, 18, 18)
                        .addComponent(j2)
                        .addGap(18, 18, 18)
                        .addComponent(jToggole))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(j9)
                        .addGap(18, 18, 18)
                        .addComponent(j6)
                        .addGap(18, 18, 18)
                        .addComponent(j3)
                        .addGap(18, 18, 18)
                        .addComponent(jDot))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jDiv)
                            .addComponent(sqrt))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jMul)
                            .addComponent(mod))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jSub)
                            .addComponent(inverse))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jAdd)
                            .addComponent(Equal))))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        j7.getAccessibleContext().setAccessibleName("J7");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void j2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j2ActionPerformed
        // TODO add your handling code here:
        //jfield.setText("");
         String enter = jfield.getText()+j2.getText();
        jfield.setText(enter);
        
    }//GEN-LAST:event_j2ActionPerformed

    private void j4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j4ActionPerformed
        // TODO add your handling code here:
       // jfield.setText("");
         String enter = jfield.getText()+j4.getText();
        jfield.setText(enter);
    }//GEN-LAST:event_j4ActionPerformed

    private void j7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j7ActionPerformed
        // TODO add your handling code here:
       // jfield.setText("");
         String enter = jfield.getText()+j7.getText();
        jfield.setText(enter);
    }//GEN-LAST:event_j7ActionPerformed

    private void j1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j1ActionPerformed

        // TODO add your handling code here:
       // jfield.setText("");
        String enter = jfield.getText()+j1.getText();
        jfield.setText(enter);
        
    }//GEN-LAST:event_j1ActionPerformed

    private void MCbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MCbuttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MCbuttonActionPerformed

    private void j8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j8ActionPerformed
        // TODO add your handling code here:
        //jfield.setText("");
         String enter = jfield.getText()+j8.getText();
        jfield.setText(enter);
    }//GEN-LAST:event_j8ActionPerformed

    private void sqrtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sqrtActionPerformed
        
        calculation = 6;
        
        operation = "sqrt";
    }//GEN-LAST:event_sqrtActionPerformed

    private void jfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jfieldActionPerformed

    private void j3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j3ActionPerformed
        // TODO add your handling code here:
        //jfield.setText("");
         String enter = jfield.getText()+j3.getText();
        jfield.setText(enter);
    }//GEN-LAST:event_j3ActionPerformed

    private void j5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j5ActionPerformed
        // TODO add your handling code here:
       // jfield.setText(""); 
        String enter = jfield.getText()+j5.getText();
        jfield.setText(enter);
    }//GEN-LAST:event_j5ActionPerformed

    private void j6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j6ActionPerformed
        // TODO add your handling code here:
        //jfield.setText("");
         String enter = jfield.getText()+j6.getText();
        jfield.setText(enter);
    }//GEN-LAST:event_j6ActionPerformed

    private void j9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j9ActionPerformed
        // TODO add your handling code here:
        //jfield.setText("");
         String enter = jfield.getText()+j9.getText();
        jfield.setText(enter);
    }//GEN-LAST:event_j9ActionPerformed

    private void j0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j0ActionPerformed
        // TODO add your handling code here:
        //jfield.setText("");
         String enter = jfield.getText()+j0.getText();
        jfield.setText(enter);
    }//GEN-LAST:event_j0ActionPerformed

    private void jAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAddActionPerformed
        // TODO add your handling code here:
        //jfield.setText("");
        num =Double.parseDouble(jfield.getText());
        //res = res+num;
        //jfield.setText("k"+num);
        calculation = 1;
        jfield.setText("");
        jLabel1.setText(num + " + ");
        operation = "+";
        
    }//GEN-LAST:event_jAddActionPerformed

    private void jSubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSubActionPerformed
       num =Double.parseDouble(jfield.getText());
        calculation = 2;
        jfield.setText("");
        jLabel1.setText(num + " - ");
        operation = "-";
    }//GEN-LAST:event_jSubActionPerformed

    private void jMulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMulActionPerformed
        num =Double.parseDouble(jfield.getText());
        calculation = 3;
        jfield.setText("");
        jLabel1.setText(num + " * ");
        operation = "*";
    }//GEN-LAST:event_jMulActionPerformed

    private void jDivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDivActionPerformed
        num =Double.parseDouble(jfield.getText());
        calculation = 4;
        jfield.setText("");
        jLabel1.setText(num + " / ");
        operation = "/";
            // jfield.setText(jfield.getText()+"/");
    }//GEN-LAST:event_jDivActionPerformed

    private void modActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modActionPerformed
        num =Double.parseDouble(jfield.getText());
        calculation = 5;
        jfield.setText("");
        jLabel1.setText(num + " % ");
        operation = "%";
    }//GEN-LAST:event_modActionPerformed

    private void EqualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EqualActionPerformed
        // TODO add your handling code here:
        String answer;
        last = Double.parseDouble(jfield.getText());
        if(operation == "+")
        {
            res = num + last;
            answer = String.format("%.2f", res);
            jfield.setText((answer));
        }
       else if(operation == "-")
        {
            res = num - last;
            answer = String.format("%.2f", res);
            jfield.setText((answer));
        }
       else if(operation == "*")
        {
            res = num * last;
            answer = String.format("%.2f", res);
            jfield.setText((answer));
        }
       else if(operation == "/")
        {
            res = num / last;
            answer = String.format("%.2f", res);
            jfield.setText((answer));
        }
       else if(operation == "%")
        {
            res = num % last;
            answer = String.format("%.2f", res);
            jfield.setText((answer));
        }
       else if(operation == "sqrt")
       {
            res =  Double.parseDouble(jfield.getText());
             jLabel1.setText( " sqrt "+last);
            jfield.setText(Double.toString(Math.sqrt(res)));
       }
       else if(operation.equals("7"))
       {
           res =  Double.parseDouble(jfield.getText());
           res = 1/res;
             //answer = String.format("%.2f", res);
            jfield.setText(Double.toString(res));
       }
                
        //arithmatic_operation();
        jLabel1.setText("");
        
    }//GEN-LAST:event_EqualActionPerformed

    private void CActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CActionPerformed
        // TODO add your handling code here:
        last = 0;
        jfield.setText("");
    }//GEN-LAST:event_CActionPerformed

    private void jDotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDotActionPerformed
        // TODO add your handling code here:
        //jfield.setText("");
         jfield.setText(jfield.getText()+".");
    }//GEN-LAST:event_jDotActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
        disable();
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void MRbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MRbuttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MRbuttonActionPerformed

    private void MSbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MSbuttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MSbuttonActionPerformed

    private void MbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MbtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MbtnActionPerformed

    private void bckspcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bckspcActionPerformed
        // TODO add your handling code here:
        int len = jfield.getText().length();
        int num = jfield.getText().length()-1;
        String store;
        if(len>0)
        {
            StringBuilder bck = new StringBuilder(jfield.getText());
            bck.deleteCharAt(num);
            store= bck.toString();
            jfield.setText(store);
            
        }
    }//GEN-LAST:event_bckspcActionPerformed

    private void CEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CEActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
                         enable();        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jToggoleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggoleActionPerformed
        // TODO add your handling code here:
        double ops = Double.parseDouble(String.valueOf(jfield.getText()));
        ops *=(-1);
        jfield.setText(String.valueOf(ops));
    }//GEN-LAST:event_jToggoleActionPerformed

    private void inverseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inverseActionPerformed
        // TODO add your handling code here:
        operation ="7";
    }//GEN-LAST:event_inverseActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton C;
    private javax.swing.JButton CE;
    private javax.swing.JButton Equal;
    private javax.swing.JButton MCbutton;
    private javax.swing.JButton MRbutton;
    private javax.swing.JButton MSbutton;
    private javax.swing.JButton Mbtn;
    private javax.swing.JButton bckspc;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton inverse;
    private javax.swing.JButton j0;
    private javax.swing.JButton j1;
    private javax.swing.JButton j2;
    private javax.swing.JButton j3;
    private javax.swing.JButton j4;
    private javax.swing.JButton j5;
    private javax.swing.JButton j6;
    private javax.swing.JButton j7;
    private javax.swing.JButton j8;
    private javax.swing.JButton j9;
    private javax.swing.JButton jAdd;
    private javax.swing.JButton jDiv;
    private javax.swing.JButton jDot;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton jMul;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JButton jSub;
    private javax.swing.JButton jToggole;
    private javax.swing.JTextField jfield;
    private javax.swing.JButton mod;
    private javax.swing.JButton sqrt;
    // End of variables declaration//GEN-END:variables
}
